document.addEventListener('DOMContentLoaded', () => {
    var cardArray = [
        {
            name:'card-1',
            img:""
        },
        {
            name:'card-2',
            img:""
        },
        {
            name:'card-3',
            img:""
        },
        {
            name:'card-4',
            img:""
        },
        {
            name:'card-5',
            img:""
        },
        {
            name:'card-6',
            img:""
        },
        {
            name:'card-7',
            img:""
        },
        {
            name:'card-8',
            img:""
        },
        {
            name:'card-9',
            img:""
        },
        {
            name:'card-10',
            img:""
        },
        {
            name:'card-11',
            img:""
        }
    ]
})